//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDialogFlowAnswer", ReplyAction="http://tempuri.org/IService1/GetDialogFlowAnswerResponse")]
        string GetDialogFlowAnswer(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDialogFlowAnswer", ReplyAction="http://tempuri.org/IService1/GetDialogFlowAnswerResponse")]
        System.Threading.Tasks.Task<string> GetDialogFlowAnswerAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecoFromMicrophone", ReplyAction="http://tempuri.org/IService1/RecoFromMicrophoneResponse")]
        void RecoFromMicrophone();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecoFromMicrophone", ReplyAction="http://tempuri.org/IService1/RecoFromMicrophoneResponse")]
        System.Threading.Tasks.Task RecoFromMicrophoneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDetectedText", ReplyAction="http://tempuri.org/IService1/GetDetectedTextResponse")]
        string GetDetectedText();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDetectedText", ReplyAction="http://tempuri.org/IService1/GetDetectedTextResponse")]
        System.Threading.Tasks.Task<string> GetDetectedTextAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfClient.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfClient.ServiceReference2.IService1>, WpfClient.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDialogFlowAnswer(string message) {
            return base.Channel.GetDialogFlowAnswer(message);
        }
        
        public System.Threading.Tasks.Task<string> GetDialogFlowAnswerAsync(string message) {
            return base.Channel.GetDialogFlowAnswerAsync(message);
        }
        
        public void RecoFromMicrophone() {
            base.Channel.RecoFromMicrophone();
        }
        
        public System.Threading.Tasks.Task RecoFromMicrophoneAsync() {
            return base.Channel.RecoFromMicrophoneAsync();
        }
        
        public string GetDetectedText() {
            return base.Channel.GetDetectedText();
        }
        
        public System.Threading.Tasks.Task<string> GetDetectedTextAsync() {
            return base.Channel.GetDetectedTextAsync();
        }
    }
}
